#!/usr/bin/python3


import map
import view

def main():
    theMap = map.Map()
    theMap.init()
    theMap.setWalls(25)
    theMap.verify()
    p1 = theMap.setRandomPlayer(1)
    p2 = theMap.setRandomPlayer(2)
    
    theView = view.View(theMap,p1,p2)
    
    theView.draw()



if __name__ == "__main__":
    main()
