#!/usr/bin/python3


import map
import view

def main():
    theMap = map.Map()
    theMap.init()
    theMap.setWalls(25)
    theMap.verify()
    p1 = theMap.setRandomPlayer()
    
    theView = view.View(theMap,p1)
    
    theView.draw()



if __name__ == "__main__":
    main()
